import firebase from 'firebase/compat/app'
import 'firebase/compat/firestore'

const firebaseConfig = {
  /* Copy your firebase config here */
};
firebase.initializeApp(firebaseConfig);

const firestoreDb = firebase.firestore()

export const getAllPosts = async () => {
  // get all + where to filter for owner
  // TO-DO
  return []
}

export const createPost = async (post) => {
  // add a doc with an autogenerated id
  // TO-DO
}

export const deletePost = async (postId) => {
  // delete a doc with the previously used autogenerated id
  // TO-DO
}

export const likePost = async (postId) => {
  // update a doc with a counter, race conditions
  // TO-DO
}

export default database